import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import type { Submission } from './types'

export async function exportSubmissionToPdf(submission: Submission): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create()
  const page = pdfDoc.addPage([595, 842])
  const { height } = page.getSize()
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  let y = height - 48
  const left = 44

  const drawLine = (text: string, opts?: { bold?: boolean; size?: number; color?: [number, number, number] }) => {
    const size = opts?.size ?? 10
    const chosen = opts?.bold ? bold : font
    const [r, g, b] = opts?.color ?? [0.12, 0.16, 0.2]
    page.drawText(text, { x: left, y, size, font: chosen, color: rgb(r, g, b) })
    y -= size + 6
  }

  const data = submission.data ?? {}
  drawLine('EXP Weekly Regional Update', { bold: true, size: 16, color: [0.06, 0.27, 0.45] })
  drawLine(`Region: ${submission.region}`, { bold: true })
  drawLine(`Week: ${submission.week_label}`)
  drawLine(`PO Name(s): ${submission.profile?.full_name ?? data.po_names ?? 'Unknown'}`)
  drawLine(`Status: ${String(data.overall_status ?? 'unknown').replace('_', ' ')}`)
  drawLine('')

  drawLine('Top Win', { bold: true })
  drawLine(String(data.top_win ?? 'Not provided'))
  drawLine('Top Challenge', { bold: true })
  drawLine(String(data.top_challenge ?? 'Not provided'))
  drawLine('')

  drawLine('Retention Snapshot', { bold: true })
  drawLine(`Scholar retention: ${Number(data.scholar_retention?.retention_rate ?? 0).toFixed(1)}%`)
  drawLine(`Mentor retention: ${Number(data.mentor_retention?.retention_rate ?? 0).toFixed(1)}%`)
  drawLine('')

  drawLine('Next Week Priorities', { bold: true })
  const priorities = Array.isArray(data.next_week_priorities) ? data.next_week_priorities : []
  if (priorities.length === 0) {
    drawLine('- Not provided')
  } else {
    priorities.slice(0, 3).forEach((p) => drawLine(`- ${String(p)}`))
  }

  drawLine('')
  drawLine('Generated by EXP Weekly Regional Update Platform', { size: 9, color: [0.4, 0.44, 0.5] })

  return pdfDoc.save()
}
