name: Secret Scan

on:
  pull_request:
    branches: [main, staging, develop]
  push:
    branches: [main, staging, develop]

jobs:
  gitleaks:
    name: Detect Secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@dcedce43c6f43de0b836d1fe38946645c9c638dc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
